### ISSUE TITLE
Can't compile with go 1.3-devel

### ISSUE THREAD

**Issue by bvtrach** [hanwen/go-mtpfs#64]
I'm trying to compile go-mtpfs with libusb 1.0.18 and the following version of go

```
% go version
go version devel +2cd1027581fa Sun May 18 05:57:40 2014 +0900 linux/amd64
```

The compilation errors are:

```
# github.com/hanwen/go-mtpfs/usb
/tmp/go/src/github.com/hanwen/go-mtpfs/usb/usb.go:475: cannot use &r (type **[0]byte) as type **C.libusb_context in argument to _Cfunc_libusb_init
/tmp/go/src/github.com/hanwen/go-mtpfs/usb/usb.go:484: cannot use c.me() (type *[0]byte) as type *C.libusb_context in argument to _Cfunc_libusb_set_debug
/tmp/go/src/github.com/hanwen/go-mtpfs/usb/usb.go:488: cannot use c.me() (type *[0]byte) as type *C.libusb_context in argument to _Cfunc_libusb_exit
/tmp/go/src/github.com/hanwen/go-mtpfs/usb/usb.go:499: cannot use c.me() (type *[0]byte) as type *C.libusb_context in argument to _Cfunc_libusb_get_device_list
```

But it compiles fine if I change the definition of Context to `type Context C.libusb_context` and Context.me() to:

``` go
func (c *Context) me() *C.libusb_context {
        return (*C.libusb_context)(c)
}
```
