### ISSUE TITLE
Errors Compiling

### ISSUE THREAD

**Issue by JSMike** [hanwen/go-mtpfs#47]
Hello,

I'm failing to compile because there are too many errors:

I received the same error using your instructions, and when using:
apt-get source --compile go-mtpfs 
after adding ppa and getting all the dependencies installed
# 

mikescc:~$ go get github.com/hanwen/go-mtpfs
# github.com/hanwen/go-mtpfs

src/github.com/hanwen/go-mtpfs/fs.go:28: undefined: Device
src/github.com/hanwen/go-mtpfs/fs.go:29: undefined: DeviceStorage
src/github.com/hanwen/go-mtpfs/fs.go:39: undefined: Device
src/github.com/hanwen/go-mtpfs/fs.go:39: undefined: DeviceStorage
src/github.com/hanwen/go-mtpfs/fs.go:133: undefined: DeviceStorage
src/github.com/hanwen/go-mtpfs/fs.go:143: undefined: File
src/github.com/hanwen/go-mtpfs/fs.go:143: undefined: DeviceStorage
src/github.com/hanwen/go-mtpfs/fs.go:202: undefined: DeviceStorage
src/github.com/hanwen/go-mtpfs/fs.go:218: undefined: File
src/github.com/hanwen/go-mtpfs/fs.go:508: undefined: File
src/github.com/hanwen/go-mtpfs/fs.go:508: too many error
# 

FYI, doing this build on an ARM chromebook with Ubuntu 12.04 since no binaries were available for armhf. 

Thanks for any help.
-Mike

**Comment by hanwen** [comment]
closing due to age.
