### ISSUE TITLE
Can't compile on debian wheezy, because wheezy has go version 1.0.2

### ISSUE THREAD

**Issue by john1498** [hanwen/go-mtpfs#71]
I get the following error:

/usr/lib/go/src/pkg/github.com/hanwen/go-fuse/fuse/bufferpool.go:41: undefined: sync.Pool
/usr/lib/go/src/pkg/github.com/hanwen/go-fuse/fuse/bufferpool.go:54: undefined: sync.Pool
/usr/lib/go/src/pkg/github.com/hanwen/go-fuse/fuse/server.go:44: undefined: sync.Pool
/usr/lib/go/src/pkg/github.com/hanwen/go-fuse/fuse/server.go:47: undefined: sync.Pool

What version of go-mtpfs could I compile with go 1.0.2? How would I go about this?
